// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define ID_CMD_SIGMA 2 
#define ID_CMD_SIGMA_LabelTitle_RESID 60001
#define ID_CMD_SIGMA_LargeImages_RESID 60002
#define ID_CMD_PIMUL 3 
#define ID_CMD_PIMUL_LabelTitle_RESID 60003
#define ID_CMD_PIMUL_LargeImages_RESID 60004
#define ID_CMD_UPPER_INDEX 4 
#define ID_CMD_UPPER_INDEX_LabelTitle_RESID 60005
#define ID_CMD_UPPER_INDEX_LargeImages_RESID 60006
#define ID_CMD_LOWER_INDEX 5 
#define ID_CMD_LOWER_INDEX_LabelTitle_RESID 60007
#define ID_CMD_LOWER_INDEX_LargeImages_RESID 60008
#define ID_CMD_FRACTION 6 
#define ID_CMD_FRACTION_LabelTitle_RESID 60009
#define ID_CMD_FRACTION_LargeImages_RESID 60010
#define ID_CMD_SQRT 7 
#define ID_CMD_SQRT_LabelTitle_RESID 60011
#define ID_CMD_SQRT_LargeImages_RESID 60012
#define ID_CMD_SIN 8 
#define ID_CMD_SIN_LabelTitle_RESID 60013
#define ID_CMD_SIN_LargeImages_RESID 60014
#define ID_CMD_COS 9 
#define ID_CMD_COS_LabelTitle_RESID 60015
#define ID_CMD_COS_LargeImages_RESID 60016
#define ID_CMD_TAN 10 
#define ID_CMD_TAN_LabelTitle_RESID 60017
#define ID_CMD_TAN_LargeImages_RESID 60018
#define ID_CMD_CTG 11 
#define ID_CMD_CTG_LabelTitle_RESID 60019
#define ID_CMD_CTG_LargeImages_RESID 60020
#define ID_CMD_ACCEPT 12 
#define ID_CMD_ACCEPT_LabelTitle_RESID 60021
#define ID_CMD_ACCEPT_LargeImages_RESID 60022
#define ID_CMD_REJECT 13 
#define ID_CMD_REJECT_LabelTitle_RESID 60023
#define ID_CMD_REJECT_LargeImages_RESID 60024
#define ID_CMD_Y_FX 14 
#define ID_CMD_Y_FX_LabelTitle_RESID 60025
#define ID_CMD_Y_FX_LargeImages_RESID 60026
#define ID_CMD_Z_FXY 15 
#define ID_CMD_Z_FXY_LabelTitle_RESID 60027
#define ID_CMD_Z_FXY_LargeImages_RESID 60028
#define ID_CMD_XY_T 16 
#define ID_CMD_XY_T_LabelTitle_RESID 60029
#define ID_CMD_XY_T_LargeImages_RESID 60030
#define ID_CMD_XYZ_T 17 
#define ID_CMD_XYZ_T_LabelTitle_RESID 60031
#define ID_CMD_XYZ_T_LargeImages_RESID 60032
#define ID_CMD_XYZ_TL 18 
#define ID_CMD_XYZ_TL_LabelTitle_RESID 60033
#define ID_CMD_XYZ_TL_LargeImages_RESID 60034
#define ID_CMD_IMPORT 19 
#define ID_CMD_IMPORT_LabelTitle_RESID 60035
#define ID_CMD_IMPORT_LargeImages_RESID 60036
#define ID_CMD_EXPORT 20 
#define ID_CMD_EXPORT_LabelTitle_RESID 60037
#define ID_CMD_EXPORT_LargeImages_RESID 60038
#define ID_CMD_CHECK 21 
#define ID_CMD_CHECK_LabelTitle_RESID 60039
#define ID_CMD_CHECK_LargeImages_RESID 60040
#define cmdTabSymbols 22 
#define cmdTabSymbols_LabelTitle_RESID 60041
#define cmdTabPlot 23 
#define cmdTabPlot_LabelTitle_RESID 60042
#define cmdGroupSetOperations 24 
#define cmdGroupSetOperations_LabelTitle_RESID 60043
#define cmdGroupNumberOperations 25 
#define cmdGroupNumberOperations_LabelTitle_RESID 60044
#define cmdTrigonometryGroup 26 
#define cmdTrigonometryGroup_LabelTitle_RESID 60045
#define cmdActionGroup 27 
#define cmdActionGroup_LabelTitle_RESID 60046
#define cmdFunctionGroup 28 
#define cmdFunctionGroup_LabelTitle_RESID 60047
#define cmdLastGroup 29 
#define cmdLastGroup_LabelTitle_RESID 60048
#define cmdChooseFunction 30 
#define cmdChooseFunction_LabelTitle_RESID 60049
#define InternalCmd2_LabelTitle_RESID 60050
